# Generated by Django 3.0.8 on 2020-12-11 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=250, verbose_name='Улица')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('flat_number', models.IntegerField(verbose_name='Номер квартиры')),
                ('slug', models.SlugField(blank=True, verbose_name='Слаг')),
                ('level', models.IntegerField(verbose_name='Этаж')),
                ('room', models.IntegerField(verbose_name='Кол-во комнат')),
                ('square', models.FloatField(verbose_name='Площадь')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('prev_img', models.ImageField(blank=True, upload_to='flats/', verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='FlatGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gal_img', models.ImageField(blank=True, upload_to='flats/gallery/', verbose_name='Фотография')),
                ('flat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flats.Flat', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
