# Generated by Django 3.0.8 on 2020-12-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('flat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flats.Flat', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Заявка на покупку квартиры',
                'verbose_name_plural': 'Заявки на покупку квартир',
            },
        ),
    ]
