# Generated by Django 3.0.8 on 2020-12-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20201214_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='num_complex',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер дома по счёту в этом комплексе'),
        ),
    ]
