# Generated by Django 3.0.8 on 2020-12-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_house_num_complex'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='num_house',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры по счёту в этом доме'),
        ),
    ]
