# Generated by Django 3.0.8 on 2020-12-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20201211_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='flatberry', verbose_name='Слаг/Slug')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
        migrations.AddField(
            model_name='review',
            name='agency',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Agency', verbose_name='Агентство'),
            preserve_default=False,
        ),
    ]
